version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Db@123123"
      ACCEPT_EULA: "Y"
    ports:
      - "1440:1433"
  #  db:
  #    image: postgres
  #    restart: always
  #    environment:
  #      POSTGRES_PASSWORD: password
  #    ports:
  #      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
      - 8001:443
    